// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr3sDYBTpw2ym9U8G7BmsDLG6FMOBB0hw',
    appId: '1:9976576268:web:60f893d44c6841fcf8f129',
    messagingSenderId: '9976576268',
    projectId: 'bbcgroup-2fcc0',
    authDomain: 'bbcgroup-2fcc0.firebaseapp.com',
    storageBucket: 'bbcgroup-2fcc0.firebasestorage.app',
    measurementId: 'G-KMBR3KB84V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFVBEQtJhtcYPOTpCBFldGUYcu-Twli7M',
    appId: '1:9976576268:android:18eef1df693d02c0f8f129',
    messagingSenderId: '9976576268',
    projectId: 'bbcgroup-2fcc0',
    storageBucket: 'bbcgroup-2fcc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3_yqDw4Dx-b4xF46NRYhwPyLaByct9uE',
    appId: '1:9976576268:ios:64ee6c3c29d6d1faf8f129',
    messagingSenderId: '9976576268',
    projectId: 'bbcgroup-2fcc0',
    storageBucket: 'bbcgroup-2fcc0.firebasestorage.app',
    iosBundleId: 'com.example.yaani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3_yqDw4Dx-b4xF46NRYhwPyLaByct9uE',
    appId: '1:9976576268:ios:64ee6c3c29d6d1faf8f129',
    messagingSenderId: '9976576268',
    projectId: 'bbcgroup-2fcc0',
    storageBucket: 'bbcgroup-2fcc0.firebasestorage.app',
    iosBundleId: 'com.example.yaani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr3sDYBTpw2ym9U8G7BmsDLG6FMOBB0hw',
    appId: '1:9976576268:web:6b1acc4987577b3ef8f129',
    messagingSenderId: '9976576268',
    projectId: 'bbcgroup-2fcc0',
    authDomain: 'bbcgroup-2fcc0.firebaseapp.com',
    storageBucket: 'bbcgroup-2fcc0.firebasestorage.app',
    measurementId: 'G-GRRL3NDXD8',
  );

}